version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=Vulnogramm
    expose:
      - 5432
    volumes:
      - ./init-databases-tables.sh:/docker-entrypoint-initdb.d/init-databases-tables.sh
  web:
    build: ./Exsample/Exsample/.
    restart: always
    volumes:
      - .:/code
    expose:
      - 7180
    depends_on:
      - db
  frontend:
    build: ./Vulnogramm_front/vulnogramm/.
    volumes:
      - .:/frontend
    ports:
      - 3000:3000
