version: '3.5'

networks:
  default:
    ipam:
      driver: default

services:
  webserver:
    image: ${IMAGE:-ghcr.io/n57uctf/merc2023:main}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_PASSWORD
    ports:
      - "6666:80"
    volumes:
      - "./source:/var/www/html"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:12
    environment:
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: "merc"
    volumes:
      - "./db.sh:/docker-entrypoint-initdb.d/initdb.sh"
      - "./util/encoder:/tmp/encoder"
    restart: always

  adminer:
    image: adminer:4.7.8
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    ports:
      - "6667:8080"
    restart: always
